name: kos_tes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.3.1
  http: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.18.1
  location: ^5.0.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/rumah_2.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
